name: Go Compatibility

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight UTC

jobs:
  test-compatibility:
    name: Test Go Compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18, 1.19, 1.20, 1.21]
      fail-fast: false  # Continue with other tests even if one fails
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: false  # Disable cache for compatibility testing

      - name: Display Go version
        run: go version

      - name: Build
        run: go build -v ./cmd/stremax || echo "Build failed with Go ${{ matrix.go-version }}"

      - name: Run tests
        run: go test ./... || echo "Tests failed with Go ${{ matrix.go-version }}"
      
      - name: Summary
        run: |
          echo "Compatibility test completed for Go ${{ matrix.go-version }}"
          if [ -f "./stremax" ]; then
            echo "✅ Build successful"
          else
            echo "❌ Build failed"
          fi 