name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./cmd/stremax

    - name: Test
      run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Lint
      run: golint ./...

    - name: Vet
      run: go vet ./...

    - name: Format check
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          gofmt -d .
          exit 1
        fi 